name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there, since this is your first issue we would love to welcome you & thank you for your notes.'
        pr-message: 'Hi there, Thanks for submitting this pull. Your contribution is highly appreciated'
